# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a16559cb910ea474b94db312cf162045"
name = "demo"
handle = "demo-1507"
application_url = "https://deficit-determined-led-dispatch.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-09aa42f9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://deficit-determined-led-dispatch.trycloudflare.com/auth/callback",
  "https://deficit-determined-led-dispatch.trycloudflare.com/auth/shopify/callback",
  "https://deficit-determined-led-dispatch.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
